---
# Ansible Inventory Configuration
# Updated: 2025-11-19

all:
  vars:
    # Global variables for all hosts
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
    system_timezone: UTC
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1

  children:
    # Production environment
    production:
      hosts:
        web-prod-01:
          ansible_host: 10.0.1.10
          ansible_port: 22
          environment: production
          instance_type: t3.large
          region: us-east-1
        web-prod-02:
          ansible_host: 10.0.1.11
          environment: production
          instance_type: t3.large
          region: us-east-1
        db-prod-01:
          ansible_host: 10.0.2.10
          environment: production
          instance_type: m5.xlarge
          region: us-east-1
      vars:
        environment: production
        log_level: info

    # Staging environment
    staging:
      hosts:
        web-stage-01:
          ansible_host: 10.1.1.10
          environment: staging
          instance_type: t3.medium
          region: us-east-1
        db-stage-01:
          ansible_host: 10.1.2.10
          environment: staging
          instance_type: t3.large
          region: us-east-1
      vars:
        environment: staging
        log_level: debug

    # Development environment
    development:
      hosts:
        dev-01:
          ansible_host: 10.2.1.10
          environment: development
          instance_type: t3.small
          region: us-east-1
      vars:
        environment: development
        log_level: debug
        enable_auto_updates: true

    # Functional groups
    webservers:
      hosts:
        web-prod-01:
        web-prod-02:
        web-stage-01:
        dev-01:
      vars:
        app_port: 8080
        app_webserver: nginx
        app_language: php
        enable_ssl: true

    databases:
      hosts:
        db-prod-01:
        db-stage-01:
      vars:
        enable_mysql_backup: true
        mysql_user: root
        backup_retention_days: 30

    monitoring:
      hosts:
        monitoring-01:
          ansible_host: 10.0.3.10
          environment: production
          instance_type: t3.medium
          region: us-east-1
      vars:
        enable_prometheus: true
        enable_grafana: true
        enable_alertmanager: true
        monitoring_environment: production
        prometheus_retention: "15d"

    loadbalancers:
      hosts:
        lb-01:
          ansible_host: 10.0.0.10
          environment: production
          instance_type: t3.medium
          region: us-east-1
      vars:
        load_balancer_type: nginx

    cache:
      hosts:
        cache-01:
          ansible_host: 10.0.4.10
          environment: production
          instance_type: t3.small
          region: us-east-1
      vars:
        cache_service: redis

    # Role-based groups
    admin_hosts:
      hosts:
        web-prod-01:
        db-prod-01:
        monitoring-01:

    restricted_access:
      hosts:
        db-prod-01:
        db-stage-01:
