# ArgoCD Installation Configuration
# This file contains the installation instructions and configuration for ArgoCD

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    purpose: gitops

---
# Installation Notes:
#
# 1. Install ArgoCD using the official manifest:
#    kubectl create namespace argocd
#    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
#
# 2. Or use this automated script:
#    ./install-argocd.sh
#
# 3. Access ArgoCD UI:
#    kubectl port-forward svc/argocd-server -n argocd 8080:443
#    https://localhost:8080
#
# 4. Get initial admin password:
#    kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
#
# 5. Login with argocd CLI:
#    argocd login localhost:8080
#    argocd account update-password

---
# ArgoCD ConfigMap - Customize ArgoCD behavior
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Enable anonymous access (dev/staging only)
  accounts.anonymous: apiKey

  # Repository credentials template
  repositories: |
    - url: https://github.com/nkefor/2048-cicd-enterprise.git
      name: enterprise-platforms
      type: git

  # Resource customizations
  resource.customizations: |
    extensions/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        return hs

---
# ArgoCD RBAC ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Default policy
  policy.default: role:readonly

  # Custom RBAC policies
  policy.csv: |
    # Admins have full access
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow

    # Developers can manage applications in their projects
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, create, */*, allow
    p, role:developer, applications, update, */*, allow
    p, role:developer, applications, sync, */*, allow

    # Viewers can only read
    p, role:viewer, applications, get, */*, allow
    p, role:viewer, projects, get, *, allow

    # Production requires approval
    p, role:prod-deployer, applications, sync, prod/*, allow
    p, role:prod-deployer, applications, override, prod/*, deny

---
# ArgoCD Notifications ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  # Slack notification template (configure webhook URL in secret)
  service.slack: |
    token: $slack-token

  # Email notification template
  service.email: |
    host: smtp.gmail.com
    port: 587
    from: argocd@example.com

  # Notification templates
  template.app-deployed: |
    message: |
      Application {{.app.metadata.name}} has been deployed to {{.app.spec.destination.namespace}}
      Sync Status: {{.app.status.sync.status}}
      Health Status: {{.app.status.health.status}}

  template.app-sync-failed: |
    message: |
      ⚠️ Application {{.app.metadata.name}} sync FAILED
      Error: {{.app.status.operationState.message}}

---
# ArgoCD Server Ingress (Optional - for external access)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.example.com  # Change to your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443
  tls:
  - hosts:
    - argocd.example.com
    secretName: argocd-server-tls
